### ISSUE TITLE
proxy not working on server

### ISSUE THREAD

**Issue by NikhilRadadiya** [brcontainer/simple-http-proxy-csharp#1]
I'm using this proxy with html2canvas, it works well when I use it in local with Visual Studio 2015 but when I upload code to server which is AWS windows server it doesn't work there.

I'm using html2canvas for pdf generation from front-end.

M I missing something here? Please help me

**Comment by brcontainer** [comment]
@NikhilRadadiya Using you html2canvas 0.5 or 0.4 version?

**Comment by NikhilRadadiya** [comment]
@brcontainer 0.5

**Comment by brcontainer** [comment]
@NikhilRadadiya I'll fix it until Saturday, it was a "html2canvas 0.5" change that made the proxy stop working.

Note: simple-http-proxy-csharp not work with html2canvas, you probably refer to https://github.com/brcontainer/html2canvas-csharp-proxy

**Comment by brcontainer** [comment]
Moved to https://github.com/brcontainer/html2canvas-csharp-proxy/issues/2
